services:
  app:
    build: ./app
    container_name: semantic_app
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PASS=semantic
      - REDIS_PORT=6379
      - ELASTIC_HOST=http://elastic:9200
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      - redis
      - elastic
  redis:
    image: redis:8.2.1
    container_name: semantic_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: 
      - redis_data:/data/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 3

  elastic: 
    image: elasticsearch:8.17.10
    container_name: semantic_elastic
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_data:/data/elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: semantic_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic


volumes:
  redis_data:
  elastic_data:
